Fix/permission infinite loop (#831)
* fix: stop infinite loop in read a non existant record

* fix: adding tests and use null for non existant records

* chore: fix lint

* build: allow "sed" on both linux and mac

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,17 +5,18 @@ git:
     submodules: false
 
 before_install:
-  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
-  - git submodule update --init --recursive
-  - gem install fpm --conservative || echo "FPM install failed"
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+      sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
       if [ "$CC" == "gcc" ]; then
         export CC=$(ls -t /usr/local/bin/gcc-?.?);
       fi
     fi
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
+      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
       export CXX=g++-4.8;
     fi
+  - git submodule update --init --recursive
+  - gem install fpm --conservative || echo "FPM install failed"
 
 compiler:
   - gcc
